create table KD13_CONF_SESS_T (
      SESS_ID DECIMAL(10) PRIMARY KEY
    , TITLE VARCHAR(60) NOT NULL
    , SESS_DATE DATE
    , START_TIME TIME
    , END_TIME TIME
    , ROOM VARCHAR(20)
    , SESS_TYPE_CODE VARCHAR(4)
    , DESCRIPTION VARCHAR(2000)
)
/