create table KD13_CONF_SESS_T (
      SESS_ID DECIMAL(10) PRIMARY KEY
    , TITLE VARCHAR(60) NOT NULL
    , SESS_DATE DATE
    , START_TIME TIME
    , END_TIME TIME
    , ROOM VARCHAR(20)
    , SESS_TYPE_CODE VARCHAR(4)
    , DESCRIPTION VARCHAR(2000)
)
/
CREATE TABLE KD13_PRESENTER_T
    ( PRES_ID VARCHAR(10) PRIMARY KEY
    , NAME VARCHAR(40)
    , INSTITUTION VARCHAR(40)
    , TITLE VARCHAR(40)
)
/
CREATE TABLE KD13_SESS_PRES_T
    ( SESS_PRES_ID DECIMAL(10) PRIMARY KEY
    , SESS_ID DECIMAL(10)      
    , PRES_ID VARCHAR(10)
    , PRIMARY_IND CHAR(1) DEFAULT 'N'
)
/
