create table KD13_CONF_SESS_T (
      SESS_ID DECIMAL(10) PRIMARY KEY
    , TITLE VARCHAR(60) NOT NULL
    , SESS_DATE DATE
    , START_TIME VARCHAR(8)
    , END_TIME VARCHAR(8)
    , ROOM VARCHAR(20)
    , SESS_TYPE_CODE VARCHAR(4)
    , DESCRIPTION VARCHAR(2000)
)
/


CREATE TABLE KD13_PRESENTER_T
    ( PRES_ID VARCHAR(10) PRIMARY KEY
    , NAME VARCHAR(40)
    , INSTITUTION VARCHAR(40)
    , TITLE VARCHAR(40)
)
/


CREATE TABLE KD13_SESS_PRES_T
    ( SESS_PRES_ID DECIMAL(10) PRIMARY KEY
    , SESS_ID DECIMAL(10)      
    , PRES_ID VARCHAR(10)
    , PRIMARY_IND CHAR(1) DEFAULT 'N'
)
/


CREATE TABLE KD13_CONF_SESS_ID_S  ( 
	id	bigint(19) AUTO_INCREMENT NOT NULL,
	PRIMARY KEY(id)
)
ENGINE = MyISAM
AUTO_INCREMENT = 1000
/


CREATE TABLE KD13_PRESENTER_ID_S  ( 
	id	bigint(19) AUTO_INCREMENT NOT NULL,
	PRIMARY KEY(id)
)
ENGINE = MyISAM
AUTO_INCREMENT = 2000
/


CREATE TABLE KD13_SESS_PRES_ID_S  ( 
	id	bigint(19) AUTO_INCREMENT NOT NULL,
	PRIMARY KEY(id)
)
ENGINE = MyISAM
AUTO_INCREMENT = 3000
/
