INSERT INTO KD13_CONF_SESS_T(SESS_ID, TITLE, SESS_DATE, START_TIME, END_TIME, ROOM, SESS_TYPE_CODE, DESCRIPTION)
VALUES('1', 'Ready, Set, KRAD!', '2013-11-21', '11:00:00', '11:45:00', 'Some Room', 'TECH', 'Desc')
/

INSERT INTO KD13_PRESENTER_T(PRES_ID, NAME, INSTITUTION, TITLE) 
	VALUES('1', 'Eric Westfall', 'Indiana University', 'Enterprise Application Architect')
/
INSERT INTO KD13_PRESENTER_T(PRES_ID, NAME, INSTITUTION, TITLE) 
	VALUES('2', 'Jonathan Keller', 'UC Davis', 'Systems Architect')
/

INSERT INTO KD13_SESS_PRES_ID_S VALUES(0)
/
INSERT INTO KD13_SESS_PRES_T(SESS_PRES_ID, SESS_ID, PRES_ID, PRIMARY_IND) 
	VALUES(LAST_INSERT_ID(), 1, '1', 'Y')
/
INSERT INTO KD13_SESS_PRES_ID_S VALUES(0)
/
INSERT INTO KD13_SESS_PRES_T(SESS_PRES_ID, SESS_ID, PRES_ID, PRIMARY_IND) 
	VALUES(LAST_INSERT_ID(), 1, '2', 'N')
/

